In [1]:
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Activation, Layer,Lambda

In [2]:
forestfires=pd.read_csv(r'C:\ExcelR\Data Scientist\Neural Network\forestfires.csv',encoding= 'unicode_escape')

In [3]:
forestfires.head()

,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,...,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep,size_category
0,mar,fri,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,...,0,0,0,0,1,0,0,0,0,small
1,oct,tue,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,...,0,0,0,0,0,0,0,1,0,small
2,oct,sat,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,...,0,0,0,0,0,0,0,1,0,small
3,mar,fri,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,...,0,0,0,0,1,0,0,0,0,small
4,mar,sun,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,...,0,0,0,0,1,0,0,0,0,small

In [4]:
forestfires.shape

(517, 31)

In [5]:
forestfires.columns

Index(['month', 'day', 'FFMC', 'DMC', 'DC', 'ISI', 'temp', 'RH', 'wind',
       'rain', 'area', 'dayfri', 'daymon', 'daysat', 'daysun', 'daythu',
       'daytue', 'daywed', 'monthapr', 'monthaug', 'monthdec', 'monthfeb',
       'monthjan', 'monthjul', 'monthjun', 'monthmar', 'monthmay', 'monthnov',
       'monthoct', 'monthsep', 'size_category'],
      dtype='object')

In [6]:
forestfires=forestfires.drop({'dayfri', 'daymon', 'daysat', 'daysun', 'daythu',
       'daytue', 'daywed', 'monthapr', 'monthaug', 'monthdec', 'monthfeb',
       'monthjan', 'monthjul', 'monthjun', 'monthmar', 'monthmay', 'monthnov',
       'monthoct', 'monthsep'}, axis=1)

In [7]:
forestfires

,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area,size_category
0,mar,fri,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,0.00,small
1,oct,tue,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,0.00,small
2,oct,sat,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,0.00,small
3,mar,fri,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,0.00,small
4,mar,sun,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,0.00,small
...,...,...,...,...,...,...,...,...,...,...,...,...
512,aug,sun,81.6,56.7,665.6,1.9,27.8,32,2.7,0.0,6.44,large
513,aug,sun,81.6,56.7,665.6,1.9,21.9,71,5.8,0.0,54.29,large
514,aug,sun,81.6,56.7,665.6,1.9,21.2,70,6.7,0.0,11.16,large
515,aug,sat,94.4,146.0,614.7,11.3,25.6,42,4.0,0.0,0.00,small
516,nov,tue,79.5,3.0,106.7,1.1,11.8,31,4.5,0.0,0.00,small

In [8]:
forestfires.isnull().sum()

month            0
day              0
FFMC             0
DMC              0
DC               0
ISI              0
temp             0
RH               0
wind             0
rain             0
area             0
size_category    0
dtype: int64

In [9]:
forestfires.describe()

,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area
count,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000
mean,90.644681,110.872340,547.940039,9.021663,18.889168,44.288201,4.017602,0.021663,12.847292
std,5.520111,64.046482,248.066192,4.559477,5.806625,16.317469,1.791653,0.295959,63.655818
min,18.700000,1.100000,7.900000,0.000000,2.200000,15.000000,0.400000,0.000000,0.000000
25%,90.200000,68.600000,437.700000,6.500000,15.500000,33.000000,2.700000,0.000000,0.000000
50%,91.600000,108.300000,664.200000,8.400000,19.300000,42.000000,4.000000,0.000000,0.520000
75%,92.900000,142.400000,713.900000,10.800000,22.800000,53.000000,4.900000,0.000000,6.570000
max,96.200000,291.300000,860.600000,56.100000,33.300000,100.000000,9.400000,6.400000,1090.840000

In [10]:
print("correlation:",forestfires.corr(method='pearson'))

correlation:           FFMC       DMC        DC       ISI      temp        RH      wind  \
FFMC  1.000000  0.382619  0.330512  0.531805  0.431532 -0.300995 -0.028485
DMC   0.382619  1.000000  0.682192  0.305128  0.469594  0.073795 -0.105342
DC    0.330512  0.682192  1.000000  0.229154  0.496208 -0.039192 -0.203466
ISI   0.531805  0.305128  0.229154  1.000000  0.394287 -0.132517  0.106826
temp  0.431532  0.469594  0.496208  0.394287  1.000000 -0.527390 -0.227116
RH   -0.300995  0.073795 -0.039192 -0.132517 -0.527390  1.000000  0.069410
wind -0.028485 -0.105342 -0.203466  0.106826 -0.227116  0.069410  1.000000
rain  0.056702  0.074790  0.035861  0.067668  0.069491  0.099751  0.061119
area  0.040122  0.072994  0.049383  0.008258  0.097844 -0.075519  0.012317

          rain      area
FFMC  0.056702  0.040122
DMC   0.074790  0.072994
DC    0.035861  0.049383
ISI   0.067668  0.008258
temp  0.069491  0.097844
RH    0.099751 -0.075519
wind  0.061119  0.012317
rain  1.000000 -0.007366
area -0.007366  1.000000

In [11]:
#We are going to perform label encoding since it is faster than dummy variables

from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
forestfires.month= label_encoder.fit_transform(forestfires.month) 
forestfires.day= label_encoder.fit_transform(forestfires.day) 
forestfires.size_category= label_encoder.fit_transform(forestfires.size_category) 
forestfires.head()

,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area,size_category
0,7,0,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,0.0,1
1,10,5,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,0.0,1
2,10,2,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,0.0,1
3,7,0,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,0.0,1
4,7,3,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,0.0,1

In [12]:
def norm_func(i):
    x = (i-i.min())/(i.max()-i.min())
    return(x)

In [13]:
pred = forestfires.iloc[:,0:11]
target = forestfires.iloc[:,11]

In [14]:
pred1 = norm_func(pred)

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(pred1,target,test_size=0.3,stratify = target)

In [16]:
# create model
model = Sequential()
model.add(Dense(14, input_dim=11, kernel_initializer='uniform', activation='relu'))
model.add(Dense(12,kernel_initializer='uniform', activation='relu'))
model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
# Fit the model
hist = model.fit(x_train, y_train, validation_split=0.33, epochs=50, batch_size=10)

Epoch 1/50
25/25 [==============================] - 3s 43ms/step - loss: 0.6898 - accuracy: 0.7054 - val_loss: 0.6836 - val_accuracy: 0.7667
Epoch 2/50
25/25 [==============================] - 0s 18ms/step - loss: 0.6791 - accuracy: 0.7137 - val_loss: 0.6623 - val_accuracy: 0.7667
Epoch 3/50
25/25 [==============================] - 0s 14ms/step - loss: 0.6568 - accuracy: 0.7137 - val_loss: 0.6222 - val_accuracy: 0.7667
Epoch 4/50
25/25 [==============================] - 0s 15ms/step - loss: 0.6264 - accuracy: 0.7137 - val_loss: 0.5797 - val_accuracy: 0.7667
Epoch 5/50
25/25 [==============================] - 0s 14ms/step - loss: 0.6110 - accuracy: 0.7137 - val_loss: 0.5621 - val_accuracy: 0.7667
Epoch 6/50
25/25 [==============================] - 0s 16ms/step - loss: 0.6038 - accuracy: 0.7137 - val_loss: 0.5496 - val_accuracy: 0.7667
Epoch 7/50
25/25 [==============================] - 0s 10ms/step - loss: 0.6021 - accuracy: 0.7137 - val_loss: 0.5462 - val_accuracy: 0.7667
Epoch 8/50
25/25 [==============================] - 0s 10ms/step - loss: 0.6015 - accuracy: 0.7137 - val_loss: 0.5443 - val_accuracy: 0.7667
Epoch 9/50
25/25 [==============================] - 0s 10ms/step - loss: 0.6024 - accuracy: 0.7137 - val_loss: 0.5510 - val_accuracy: 0.7667
Epoch 10/50
25/25 [==============================] - 0s 9ms/step - loss: 0.6005 - accuracy: 0.7137 - val_loss: 0.5477 - val_accuracy: 0.7667
Epoch 11/50
25/25 [==============================] - 0s 10ms/step - loss: 0.6010 - accuracy: 0.7137 - val_loss: 0.5517 - val_accuracy: 0.7667
Epoch 12/50
25/25 [==============================] - 0s 9ms/step - loss: 0.6007 - accuracy: 0.7137 - val_loss: 0.5464 - val_accuracy: 0.7667
Epoch 13/50
25/25 [==============================] - 0s 11ms/step - loss: 0.5997 - accuracy: 0.7137 - val_loss: 0.5459 - val_accuracy: 0.7667
Epoch 14/50
25/25 [==============================] - 0s 10ms/step - loss: 0.6002 - accuracy: 0.7137 - val_loss: 0.5441 - val_accuracy: 0.7667
Epoch 15/50
25/25 [==============================] - 0s 9ms/step - loss: 0.5990 - accuracy: 0.7137 - val_loss: 0.5448 - val_accuracy: 0.7667
Epoch 16/50
25/25 [==============================] - 0s 9ms/step - loss: 0.5993 - accuracy: 0.7137 - val_loss: 0.5431 - val_accuracy: 0.7667
Epoch 17/50
25/25 [==============================] - 0s 10ms/step - loss: 0.5969 - accuracy: 0.7137 - val_loss: 0.5492 - val_accuracy: 0.7667
Epoch 18/50
25/25 [==============================] - 0s 10ms/step - loss: 0.5979 - accuracy: 0.7137 - val_loss: 0.5527 - val_accuracy: 0.7667
Epoch 19/50
25/25 [==============================] - 0s 12ms/step - loss: 0.5975 - accuracy: 0.7137 - val_loss: 0.5477 - val_accuracy: 0.7667
Epoch 20/50
25/25 [==============================] - 0s 10ms/step - loss: 0.5972 - accuracy: 0.7137 - val_loss: 0.5452 - val_accuracy: 0.7667
Epoch 21/50
25/25 [==============================] - 0s 11ms/step - loss: 0.5964 - accuracy: 0.7137 - val_loss: 0.5450 - val_accuracy: 0.7667
Epoch 22/50
25/25 [==============================] - 0s 5ms/step - loss: 0.5965 - accuracy: 0.7137 - val_loss: 0.5430 - val_accuracy: 0.7667
Epoch 23/50
25/25 [==============================] - 0s 6ms/step - loss: 0.5953 - accuracy: 0.7137 - val_loss: 0.5475 - val_accuracy: 0.7667
Epoch 24/50
25/25 [==============================] - 0s 6ms/step - loss: 0.5965 - accuracy: 0.7137 - val_loss: 0.5489 - val_accuracy: 0.7667
Epoch 25/50
25/25 [==============================] - 0s 5ms/step - loss: 0.5965 - accuracy: 0.7137 - val_loss: 0.5423 - val_accuracy: 0.7667
Epoch 26/50
25/25 [==============================] - 0s 5ms/step - loss: 0.5950 - accuracy: 0.7137 - val_loss: 0.5427 - val_accuracy: 0.7667
Epoch 27/50
25/25 [==============================] - 0s 7ms/step - loss: 0.5944 - accuracy: 0.7137 - val_loss: 0.5449 - val_accuracy: 0.7667
Epoch 28/50
25/25 [==============================] - 0s 7ms/step - loss: 0.5939 - accuracy: 0.7137 - val_loss: 0.5437 - val_accuracy: 0.7667
Epoch 29/50
25/25 [==============================] - 0s 6ms/step - loss: 0.5954 - accuracy: 0.7137 - val_loss: 0.5478 - val_accuracy: 0.7667
Epoch 30/50
25/25 [==============================] - 0s 6ms/step - loss: 0.5928 - accuracy: 0.7137 - val_loss: 0.5454 - val_accuracy: 0.7667
Epoch 31/50
25/25 [==============================] - 0s 6ms/step - loss: 0.5924 - accuracy: 0.7137 - val_loss: 0.5450 - val_accuracy: 0.7667
Epoch 32/50
25/25 [==============================] - 0s 7ms/step - loss: 0.5920 - accuracy: 0.7137 - val_loss: 0.5434 - val_accuracy: 0.7667
Epoch 33/50
25/25 [==============================] - 0s 10ms/step - loss: 0.5915 - accuracy: 0.7137 - val_loss: 0.5495 - val_accuracy: 0.7667
Epoch 34/50
25/25 [==============================] - 0s 7ms/step - loss: 0.5905 - accuracy: 0.7137 - val_loss: 0.5471 - val_accuracy: 0.7667
Epoch 35/50
25/25 [==============================] - 0s 6ms/step - loss: 0.5904 - accuracy: 0.7137 - val_loss: 0.5470 - val_accuracy: 0.7667
Epoch 36/50
25/25 [==============================] - 0s 6ms/step - loss: 0.5914 - accuracy: 0.7137 - val_loss: 0.5443 - val_accuracy: 0.7667
Epoch 37/50
25/25 [==============================] - 0s 7ms/step - loss: 0.5897 - accuracy: 0.7137 - val_loss: 0.5458 - val_accuracy: 0.7667
Epoch 38/50
25/25 [==============================] - 0s 5ms/step - loss: 0.5888 - accuracy: 0.7137 - val_loss: 0.5438 - val_accuracy: 0.7667
Epoch 39/50
25/25 [==============================] - 0s 4ms/step - loss: 0.5877 - accuracy: 0.7137 - val_loss: 0.5477 - val_accuracy: 0.7667
Epoch 40/50
25/25 [==============================] - 0s 4ms/step - loss: 0.5872 - accuracy: 0.7137 - val_loss: 0.5454 - val_accuracy: 0.7667
Epoch 41/50
25/25 [==============================] - 0s 7ms/step - loss: 0.5876 - accuracy: 0.7137 - val_loss: 0.5450 - val_accuracy: 0.7667
Epoch 42/50
25/25 [==============================] - 0s 13ms/step - loss: 0.5861 - accuracy: 0.7137 - val_loss: 0.5433 - val_accuracy: 0.7667
Epoch 43/50
25/25 [==============================] - 0s 14ms/step - loss: 0.5848 - accuracy: 0.7137 - val_loss: 0.5451 - val_accuracy: 0.7667
Epoch 44/50
25/25 [==============================] - 0s 14ms/step - loss: 0.5850 - accuracy: 0.7137 - val_loss: 0.5447 - val_accuracy: 0.7667
Epoch 45/50
25/25 [==============================] - 0s 14ms/step - loss: 0.5847 - accuracy: 0.7137 - val_loss: 0.5476 - val_accuracy: 0.7667
Epoch 46/50
25/25 [==============================] - 0s 14ms/step - loss: 0.5834 - accuracy: 0.7137 - val_loss: 0.5468 - val_accuracy: 0.7667
Epoch 47/50
25/25 [==============================] - 0s 17ms/step - loss: 0.5818 - accuracy: 0.7137 - val_loss: 0.5440 - val_accuracy: 0.7667
Epoch 48/50
25/25 [==============================] - 0s 13ms/step - loss: 0.5815 - accuracy: 0.7137 - val_loss: 0.5471 - val_accuracy: 0.7667
Epoch 49/50
25/25 [==============================] - 0s 13ms/step - loss: 0.5811 - accuracy: 0.7137 - val_loss: 0.5497 - val_accuracy: 0.7667
Epoch 50/50
25/25 [==============================] - 0s 13ms/step - loss: 0.5835 - accuracy: 0.7137 - val_loss: 0.5436 - val_accuracy: 0.7667

In [17]:
test_loss, test_acc = model.evaluate(x_test, y_test)

5/5 [==============================] - 1s 5ms/step - loss: 0.5682 - accuracy: 0.7308

In [18]:
print(hist.history.keys())

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])

In [19]:
hist_df = pd.DataFrame(hist.history)
hist_df["epoch"]=hist.epoch
hist_df.tail()

        loss  accuracy  val_loss  val_accuracy  epoch
45  0.583368  0.713693  0.546840      0.766667     45
46  0.581799  0.713693  0.543973      0.766667     46
47  0.581528  0.713693  0.547053      0.766667     47
48  0.581137  0.713693  0.549717      0.766667     48
49  0.583501  0.713693  0.543609      0.766667     49